import type {LocalizationType} from './type';

export default {
  hello: 'bonjour',
  discover: 'Discover world with us !',
  favorites_title: 'Your favorites places !',
  search_place_title: 'Result of research',
  profil: 'Profil',
  paiementMethod: 'Payment method ',
  myAnnonces: 'My places',
  firstname: 'Firstname',
  lastname: 'Lastname',
  birthdate: 'Birthdate',
  desc: 'Description',
  mail: 'Email',
  password: 'Password',
  modify: 'Modify',
  validate: 'Validate',
  personalInfo: 'Personal information',
  connexionInfo: 'Connexion information',
  promo: 'Promotional code',
  addCode: 'Add a new code',
  actif: 'Active promo',
  innactif: 'Innactive promo',
  places_title: 'Your places !',

  //Place_detail
  place_detail_about: 'About',
  place_detail_people_review_this: 'People review this',
  place_detail_see_more: 'See more',
  place_detail_features: 'Features',
  place_detail_authorization: 'Authorizations',
  place_detail_animals: 'Animals',
  place_detail_smoking: 'Smoking',
  place_detail_music: 'Music',
  place_detail_fire: 'Fire',
  place_detail_food_and_drink: 'Food and Drink',
  place_detail_location: 'Place location',
  place_detail_availavilities: 'Availabilities',
  place_detail_similar_places: 'Similar places',
  place_detail_active_bookings: 'Active bookings',
  place_detail_per_day: 'Per day',
  place_detail_see_bookings: 'See bookings',
  place_detail_book: 'Book',
} as LocalizationType;
